Repository florence-social/mastodon-fork, pull requests merged in 2019-06, with the labels that each got.

#45 i18n: 🇵🇱
  config/locales/pl.yml
Labels: A-localisation, C-admin-settings

#49 allow biography length configuration
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/settings_controller.rb
  app/helpers/application_helper.rb
  app/javascript/mastodon/initial_state.js
  app/javascript/packs/public.js
  app/models/account.rb
  app/models/form/admin_settings.rb
  app/presenters/instance_presenter.rb
  app/serializers/initial_state_serializer.rb
  app/views/admin/settings/edit.html.haml
  app/views/settings/profiles/show.html.haml
  config/locales/en.yml
  config/settings.yml
  spec/controllers/api/v1/accounts/credentials_controller_spec.rb
  spec/models/account_spec.rb
Labels: A-accessibility, A-customisation, B-instance-admin, C-admin-settings, S-glitch-social

#41 direct messages on home timeline (behind a setting)
  app/controllers/settings/preferences_controller.rb
  app/lib/feed_manager.rb
  app/lib/user_settings_decorator.rb
  app/models/user.rb
  app/services/fan_out_on_write_service.rb
  app/views/settings/preferences/show.html.haml
  config/locales/simple_form.en.yml
  config/settings.yml
  spec/lib/feed_manager_spec.rb
Labels: A-accessibility, A-customisation, C-user-settings, S-existing-changes

#85 Update CHANGELOG
  CHANGELOG.md
  lib/mastodon/version.rb
  spec/presenters/instance_presenter_spec.rb
Labels: C-documentation

#87 Update French/English strings
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/simple_form.fr.yml
Labels: A-localisation, C-admin-settings, C-user-settings

#86 Spanish translations
  config/locales/en.yml
  config/locales/es.yml
Labels: A-localisation, K-offer-upstream

#106 Typo in README.md
  README.md
Labels: C-documentation

#105 Fix incorrect merge of admin settings
  app/models/form/admin_settings.rb
Labels: C-admin-settings, V-hotfix-bump

#103 Update repo URL in places
  app.json
  config/deploy.rb
  docker-compose.yml
  package.json
  scalingo.json
Labels: V-hotfix-bump

#107 Dutch translations
  config/locales/nl.yml
  config/locales/simple_form.nl.yml
Labels: A-localisation, C-admin-settings, C-user-settings, V-hotfix-bump
