Repository florence-social/mastodon-fork, pull requests merged in 2019-08, with the labels that each got.

#163 Fix type for max_toot_chars and max_bio_chars in instance info
  app/controllers/admin/settings_controller.rb
  app/models/form/admin_settings.rb
  app/serializers/rest/instance_serializer.rb
Labels: A-compatibility, B-app-developers, C-admin-settings, C-api, K-bug, V-hotfix-bump

#164 Add 0.1.2 to changelog
  CHANGELOG.md
Labels: C-documentation

#169 Update webpack to fix set-value CVE
  yarn.lock
Labels: A-security, V-hotfix-bump
